### ISSUE TITLE
Please rename repo to buildout.wheel

### ISSUE THREAD

**Issue by leorochael** [buildout/wheel#5]
Otherwise I can't have a fork of this and of the PYPA wheel at the same time in github.

**Comment by jimfulton** [comment]
Why not just work in this org?

**Comment by jimfulton** [comment]
Anyway, I'm fine with renaming if that would make your life easier.  Let me know when you want me to do that.

**Comment by leorochael** [comment]
> Why not just work in this org?

Incidentally, I'm not in this org...

Do you mind adding me? I promise I'll be good ;-)

> Anyway, I'm fine with renaming if that would make your life easier. Let me know when you want me to do that.

Thanks for renaming... I appreciate that. It also saves me having to do

    git clone git@github.com:buildout/wheel.git buildout.wheel

Instead of just:

    git clone git@github.com:buildout/buildout.wheel.git

When I also have the PYPA wheel checked out in the same repo.

**Comment by jimfulton** [comment]
On Sun, Feb 19, 2017 at 5:15 PM, Leonardo Rochael Almeida <
notifications@github.com> wrote:

> Why not just work in this org?
>
> Incidentally, I'm not in this org...
>
> Do you mind adding me? I promise I'll be good ;-)
>

You should get an invite.
